# By Aditi Mehra
name: vpn_basic_project
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'

# App Version
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

# App dependencies
dependencies:
  flutter:
    sdk: flutter
  # getX for state management  
  get: ^4.6.5
  cupertino_icons:
  # for api call  
  http: ^1.0.0
  # converting csv data to list 
  csv: ^5.0.2
  lottie: ^2.4.0

  # for local storage database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_mobile_ads: ^3.0.0
  firebase_core: ^2.14.0
  firebase_remote_config: ^4.2.3
  rename: ^2.1.1
  

  


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Change package name  
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  hive_generator: ^2.0.0
  build_runner: ^2.4.5
  

flutter_icons:
  android: true
  image_path: "assets/icon/logo.png"

  

flutter:
  # Enabling material design
  uses-material-design: true

  # App assets
  assets:
    - assets/images/
    - assets/vpn/
    - assets/lottie/
    - assets/flags/